package jetbrains.mps.baselanguage.exprblocks.structure;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.structure.Statement;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.baseLanguage.structure.StatementList;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TransparentBlock extends Statement {
  public static final String concept = "jetbrains.mps.baselanguage.exprblocks.structure.TransparentBlock";
  public static final String SLIST = "slist";

  public TransparentBlock(SNode node) {
    super(node);
  }

  public StatementList getSlist() {
    return (StatementList) this.getChild(StatementList.class, TransparentBlock.SLIST);
  }

  public void setSlist(StatementList node) {
    super.setChild(TransparentBlock.SLIST, node);
  }

  public static TransparentBlock newInstance(SModel sm, boolean init) {
    return (TransparentBlock) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.baselanguage.exprblocks.structure.TransparentBlock", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TransparentBlock newInstance(SModel sm) {
    return TransparentBlock.newInstance(sm, false);
  }
}
