package relmapping.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Database extends BaseConcept implements INamedConcept {
  public static final String concept = "relmapping.structure.Database";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TABLES = "tables";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Database(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Database.NAME);
  }

  public void setName(String value) {
    this.setProperty(Database.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Database.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Database.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Database.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Database.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Database.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Database.VIRTUAL_PACKAGE, value);
  }

  public int getTablesesCount() {
    return this.getChildCount(Database.TABLES);
  }

  public Iterator<Table> tableses() {
    return this.children(Table.class, Database.TABLES);
  }

  public List<Table> getTableses() {
    return this.getChildren(Table.class, Database.TABLES);
  }

  public void addTables(Table node) {
    this.addChild(Database.TABLES, node);
  }

  public void insertTables(Table prev, Table node) {
    this.insertChild(prev, Database.TABLES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Database.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Database.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Database.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Database.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Database.SMODEL_ATTRIBUTE, node);
  }

  public static Database newInstance(SModel sm, boolean init) {
    return (Database) SModelUtil_new.instantiateConceptDeclaration("relmapping.structure.Database", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Database newInstance(SModel sm) {
    return Database.newInstance(sm, false);
  }
}
