package relmapping.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NumberType extends DataType {
  public static final String concept = "relmapping.structure.NumberType";

  public NumberType(SNode node) {
    super(node);
  }

  public static NumberType newInstance(SModel sm, boolean init) {
    return (NumberType) SModelUtil_new.instantiateConceptDeclaration("relmapping.structure.NumberType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NumberType newInstance(SModel sm) {
    return NumberType.newInstance(sm, false);
  }
}
