package relmapping_entities.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Relmapping_entities_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("6df20848-5706-4283-9ced-bb5528d6efdd(relmapping_entities)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
