package DummyLang.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CharList extends VarDecl {
  public static final String concept = "DummyLang.structure.CharList";
  public static final String ELEMENTS = "elements";

  public CharList(SNode node) {
    super(node);
  }

  public int getElementsesCount() {
    return this.getChildCount(CharList.ELEMENTS);
  }

  public Iterator<VarDecl> elementses() {
    return this.children(VarDecl.class, CharList.ELEMENTS);
  }

  public List<VarDecl> getElementses() {
    return this.getChildren(VarDecl.class, CharList.ELEMENTS);
  }

  public void addElements(VarDecl node) {
    this.addChild(CharList.ELEMENTS, node);
  }

  public void insertElements(VarDecl prev, VarDecl node) {
    this.insertChild(prev, CharList.ELEMENTS, node);
  }

  public static CharList newInstance(SModel sm, boolean init) {
    return (CharList) SModelUtil_new.instantiateConceptDeclaration("DummyLang.structure.CharList", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CharList newInstance(SModel sm) {
    return CharList.newInstance(sm, false);
  }
}
