package DummyLang.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class DummyLang_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("72df27fc-d185-4e9e-b8ef-9d626a9ff98b(DummyLang)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
