package de.voelter.mps.textshape.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"de.voelter.mps.textshape.structure.File", "de.voelter.mps.textshape.structure.IndentedBlock", "de.voelter.mps.textshape.structure.Line", "de.voelter.mps.textshape.structure.List", "de.voelter.mps.textshape.structure.MultiTextToken", "de.voelter.mps.textshape.structure.NeedsBlankLink", "de.voelter.mps.textshape.structure.PascalDeclaration", "de.voelter.mps.textshape.structure.PlaceHolder", "de.voelter.mps.textshape.structure.SingleTextToken", "de.voelter.mps.textshape.structure.Statement", "de.voelter.mps.textshape.structure.TextShapeConfig"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 2:
        return new Line_BehaviorDescriptor();
      case 0:
        return new File_BehaviorDescriptor();
      case 6:
        return new PascalDeclaration_BehaviorDescriptor();
      case 8:
        return new SingleTextToken_BehaviorDescriptor();
      case 4:
        return new MultiTextToken_BehaviorDescriptor();
      case 3:
        return new List_BehaviorDescriptor();
      case 1:
        return new IndentedBlock_BehaviorDescriptor();
      case 7:
        return new PlaceHolder_BehaviorDescriptor();
      case 10:
        return new TextShapeConfig_BehaviorDescriptor();
      case 9:
        return new Statement_BehaviorDescriptor();
      case 5:
        return new NeedsBlankLink_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
