package de.voelter.mps.textshape.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface IFileContent_BehaviorDescriptor {
  public SNode virtual_file_369287372546174884(SNode thisNode);
  public SNode virtual_config_5815279313395467763(SNode thisNode);
  public boolean virtual_needsBlankLine_5815279313395613799(SNode thisNode);
}
