package de.voelter.mps.textshape.behavior;

/*Generated by MPS */


public class MultiTextToken_BehaviorDescriptor extends TextToken_BehaviorDescriptor {
  public MultiTextToken_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.textshape.structure.MultiTextToken";
  }
}
