package de.voelter.mps.textshape.behavior;

/*Generated by MPS */


public class Statement_BehaviorDescriptor extends Line_BehaviorDescriptor implements IFileContent_BehaviorDescriptor, IStatement_BehaviorDescriptor {
  public Statement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.textshape.structure.Statement";
  }
}
