package de.voelter.mps.textshape.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class TextToken_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public TextToken_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.textshape.structure.TextToken";
  }
}
