package de.voelter.mps.gv.structure;

/*Generated by MPS */

import jetbrains.mps.lang.structure.structure.ConceptDeclaration;

public class AnnotationDiagram_AnnotationLink {
  public static final String ANNOTATION_DIAGRAM = "annotationDiagram";

  public static void setAnnotationDiagram(ConceptDeclaration source, DiagramAnnotation target) {
    source.setAttribute(AnnotationDiagram_AnnotationLink.ANNOTATION_DIAGRAM, target);
  }

  public static DiagramAnnotation getAnnotationDiagram(ConceptDeclaration source) {
    return (DiagramAnnotation) source.getAttribute(AnnotationDiagram_AnnotationLink.ANNOTATION_DIAGRAM);
  }
}
