package de.voelter.mps.gv.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.structure.structure.ConceptDeclaration;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ConDecRef extends BaseConcept {
  public static final String concept = "de.voelter.mps.gv.structure.ConDecRef";
  public static final String CONCEPT = "concept";

  public ConDecRef(SNode node) {
    super(node);
  }

  public ConceptDeclaration getConcept() {
    return (ConceptDeclaration) this.getReferent(ConceptDeclaration.class, ConDecRef.CONCEPT);
  }

  public void setConcept(ConceptDeclaration node) {
    super.setReferent(ConDecRef.CONCEPT, node);
  }

  public static ConDecRef newInstance(SModel sm, boolean init) {
    return (ConDecRef) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.gv.structure.ConDecRef", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ConDecRef newInstance(SModel sm) {
    return ConDecRef.newInstance(sm, false);
  }
}
