package de.voelter.mps.gv.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Gv_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("dcf3d84b-ead9-4694-abd0-78416ced3097(de.voelter.mps.gv)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
