package rbac_entities.structure;

/*Generated by MPS */

import rbac.structure.Resource;
import jetbrains.mps.smodel.SNode;
import entities.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributeResource extends Resource {
  public static final String concept = "rbac_entities.structure.AttributeResource";
  public static final String ATTRIBUTE = "attribute";

  public AttributeResource(SNode node) {
    super(node);
  }

  public Attribute getAttribute() {
    return (Attribute) this.getReferent(Attribute.class, AttributeResource.ATTRIBUTE);
  }

  public void setAttribute(Attribute node) {
    super.setReferent(AttributeResource.ATTRIBUTE, node);
  }

  public static AttributeResource newInstance(SModel sm, boolean init) {
    return (AttributeResource) SModelUtil_new.instantiateConceptDeclaration("rbac_entities.structure.AttributeResource", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributeResource newInstance(SModel sm) {
    return AttributeResource.newInstance(sm, false);
  }
}
