package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public abstract class BinaryArithmeticExpression_BehaviorDescriptor extends BinaryExpression_BehaviorDescriptor {
  public BinaryArithmeticExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.BinaryArithmeticExpression";
  }
}
