package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class BinaryExpression_Behavior {
  private static Class[] PARAMETERS_8860443239512166656 = {SNode.class};
  private static Class[] PARAMETERS_2088909457728257441 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_childTypeMustBeInstanceOf_8860443239512166656(SNode thisNode) {
    return null;
  }

  public static SNode virtual_childTypeMustBeInstanceOf2_2088909457728257441(SNode thisNode) {
    return null;
  }

  public static SNode call_childTypeMustBeInstanceOf_8860443239512166656(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getConceptDescriptorForInstanceNode(thisNode).behavior();
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.expressions.structure.BinaryExpression"), "virtual_childTypeMustBeInstanceOf_8860443239512166656", PARAMETERS_8860443239512166656);
  }

  public static SNode call_childTypeMustBeInstanceOf2_2088909457728257441(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getConceptDescriptorForInstanceNode(thisNode).behavior();
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.expressions.structure.BinaryExpression"), "virtual_childTypeMustBeInstanceOf2_2088909457728257441", PARAMETERS_2088909457728257441);
  }

  public static SNode callSuper_childTypeMustBeInstanceOf_8860443239512166656(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.expressions.structure.BinaryExpression"), callerConceptFqName, "virtual_childTypeMustBeInstanceOf_8860443239512166656", PARAMETERS_8860443239512166656);
  }

  public static SNode callSuper_childTypeMustBeInstanceOf2_2088909457728257441(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.expressions.structure.BinaryExpression"), callerConceptFqName, "virtual_childTypeMustBeInstanceOf2_2088909457728257441", PARAMETERS_2088909457728257441);
  }
}
