package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class BinaryComparisonExpression_Behavior {
  public static void init(SNode thisNode) {
  }
}
