package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class BooleanType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor implements IComparable_BehaviorDescriptor {
  public BooleanType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.BooleanType";
  }
}
