package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public abstract class BooleanLiteral_BehaviorDescriptor extends Literal_BehaviorDescriptor {
  public BooleanLiteral_BehaviorDescriptor() {
  }

  public String virtual_toText_5815279313395675462(SNode thisNode) {
    return BooleanLiteral_Behavior.virtual_toText_5815279313395675462(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.BooleanLiteral";
  }
}
