package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class DivExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public DivExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.DivExpression";
  }
}
