package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class DoubleType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor implements IComparable_BehaviorDescriptor, IOrdered_BehaviorDescriptor, INumber_BehaviorDescriptor {
  public DoubleType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.DoubleType";
  }
}
