package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class EqualsExpression_BehaviorDescriptor extends BinaryComparisonExpression_BehaviorDescriptor {
  public EqualsExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.EqualsExpression";
  }
}
