package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptPropertyOperations;

public class Expression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_needsParens_5763383285156530284(SNode thisNode) {
    SNode parent = SNodeOperations.getParent(thisNode);
    if (SNodeOperations.isInstanceOf(parent, "de.voelter.mps.expressions.structure.Expression")) {
      int parentPrio = SConceptPropertyOperations.getInteger(SNodeOperations.cast(parent, "de.voelter.mps.expressions.structure.Expression"), "priolevel");
      int thisPrio = SConceptPropertyOperations.getInteger(thisNode, "priolevel");
      return thisPrio < parentPrio;
    }
    return false;
  }
}
