package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class FalseLiteral_BehaviorDescriptor extends BooleanLiteral_BehaviorDescriptor {
  public FalseLiteral_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.FalseLiteral";
  }
}
