package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class IfExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor {
  public IfExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.IfExpression";
  }
}
