package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public interface IMemberContainer_BehaviorDescriptor {
  public SNode virtual_dotExpressionConcept_5856418980158943574(SNode thisNode);
}
