package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class IntegerLiteral_BehaviorDescriptor extends Literal_BehaviorDescriptor {
  public IntegerLiteral_BehaviorDescriptor() {
  }

  public String virtual_toText_5815279313395675462(SNode thisNode) {
    return IntegerLiteral_Behavior.virtual_toText_5815279313395675462(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.IntegerLiteral";
  }
}
