package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class IntType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor implements IComparable_BehaviorDescriptor, IOrdered_BehaviorDescriptor, INumber_BehaviorDescriptor {
  public IntType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.IntType";
  }
}
