package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class LessEqualsExpression_BehaviorDescriptor extends BinaryComparisonExpression_BehaviorDescriptor {
  public LessEqualsExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.LessEqualsExpression";
  }
}
