package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class LessExpression_BehaviorDescriptor extends BinaryComparisonExpression_BehaviorDescriptor {
  public LessExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.LessExpression";
  }
}
