package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class MinusExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public MinusExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.MinusExpression";
  }
}
