package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class MultiExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public MultiExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.MultiExpression";
  }
}
