package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class PlusExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_childTypeMustBeInstanceOf2_2088909457728257441(SNode thisNode) {
    return SConceptOperations.findConceptDeclaration("de.voelter.mps.expressions.structure.StringType");
  }
}
