package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class PlusExpression_BehaviorDescriptor extends BinaryArithmeticExpression_BehaviorDescriptor {
  public PlusExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.PlusExpression";
  }
}
