package de.voelter.mps.expressions.behavior;

/*Generated by MPS */


public class StringType_BehaviorDescriptor extends PrimitiveType_BehaviorDescriptor {
  public StringType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.StringType";
  }
}
