package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;

public class StringLiteral_BehaviorDescriptor extends Literal_BehaviorDescriptor {
  public StringLiteral_BehaviorDescriptor() {
  }

  public String virtual_toText_5815279313395675462(SNode thisNode) {
    return StringLiteral_Behavior.virtual_toText_5815279313395675462(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.StringLiteral";
  }
}
