package de.voelter.mps.expressions.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class Type_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public Type_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.expressions.structure.Type";
  }
}
