package uispec_validation.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baselanguage.exprblocks.behavior.PlaceholderStatement_Behavior;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import entities.behavior.Attribute_Behavior;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_5359815737040851452(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name").equals("pre-assign");
  }

  public static boolean baseMappingRule_Condition_5359815737040859377(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SNodeOperations.isInstanceOf(PlaceholderStatement_Behavior.call_getData_5359815737040877621(_context.getNode(), _context), "uispec_validation.structure.ValidatedField");
  }

  public static Object propertyMacro_GetPropertyValue_5359815737040876202(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(PlaceholderStatement_Behavior.call_getData_5359815737040877621(_context.getNode(), _context), "uispec.structure.Field"), "label");
  }

  public static Object referenceMacro_GetReferent_5359815737040900376(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "a" + SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(_context.getNode(), "attr", false)), "entities.structure.Entity"), "name");
  }

  public static Object referenceMacro_GetReferent_5359815737040900402(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return Attribute_Behavior.call_getterName_726639030028408915(SLinkOperations.getTarget(_context.getNode(), "attr", false));
  }

  public static Object referenceMacro_GetReferent_5359815737040911708(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "a" + SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "expr", true), "attr", false)), "entities.structure.Entity"), "name");
  }

  public static Object referenceMacro_GetReferent_5359815737040911725(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return Attribute_Behavior.call_getterName_726639030028408915(SLinkOperations.getTarget(SLinkOperations.getTarget(_context.getNode(), "expr", true), "attr", false));
  }

  public static SNode sourceNodeQuery_5359815737040900588(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "expr", true);
  }

  public static SNode sourceNodeQuery_5359815737040889216(final IOperationContext operationContext, final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(SNodeOperations.cast(PlaceholderStatement_Behavior.call_getData_5359815737040877621(_context.getNode(), _context), "uispec_validation.structure.ValidatedField"), "expr", true);
  }
}
