package de.voelter.mps.naming.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.structure.BehaviorDescriptor;
import jetbrains.mps.smodel.structure.ConceptRegistry;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

public class INamespaceContent_Behavior {
  private static Class[] PARAMETERS_5019556274771919323 = {SNode.class};
  private static Class[] PARAMETERS_5856418980158996214 = {SNode.class};

  public static void init(SNode thisNode) {
  }

  public static SNode virtual_owningNamespace_5019556274771919323(SNode thisNode) {
    return SNodeOperations.getAncestor(thisNode, "de.voelter.mps.naming.structure.Namespace", false, false);
  }

  public static boolean virtual_isExternallyVisible_5856418980158996214(SNode thisNode) {
    return true;
  }

  public static SNode call_owningNamespace_5019556274771919323(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (SNode) descriptor.invoke(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.naming.structure.INamespaceContent"), "virtual_owningNamespace_5019556274771919323", PARAMETERS_5019556274771919323);
  }

  public static boolean call_isExternallyVisible_5856418980158996214(SNode thisNode) {
    BehaviorDescriptor descriptor = ConceptRegistry.getInstance().getBehaviorDescriptorForInstanceNode(thisNode);
    return (Boolean) descriptor.invoke(Boolean.class, SNodeOperations.cast(thisNode, "de.voelter.mps.naming.structure.INamespaceContent"), "virtual_isExternallyVisible_5856418980158996214", PARAMETERS_5856418980158996214);
  }

  public static SNode callSuper_owningNamespace_5019556274771919323(SNode thisNode, String callerConceptFqName) {
    return (SNode) BehaviorManager.getInstance().invokeSuper(Object.class, SNodeOperations.cast(thisNode, "de.voelter.mps.naming.structure.INamespaceContent"), callerConceptFqName, "virtual_owningNamespace_5019556274771919323", PARAMETERS_5019556274771919323);
  }

  public static boolean callSuper_isExternallyVisible_5856418980158996214(SNode thisNode, String callerConceptFqName) {
    return (Boolean) BehaviorManager.getInstance().invokeSuper(Boolean.class, SNodeOperations.cast(thisNode, "de.voelter.mps.naming.structure.INamespaceContent"), callerConceptFqName, "virtual_isExternallyVisible_5856418980158996214", PARAMETERS_5856418980158996214);
  }
}
