package de.voelter.mps.naming.behavior;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.smodel.SNode;

public interface INamespace_BehaviorDescriptor extends INamespaceContent_BehaviorDescriptor {
  public List<SNode> virtual_siblings_7517722170421689483(SNode thisNode);
  public List<SNode> virtual_allVisibleNode_7517722170421689521(SNode thisNode, SNode ofType);
  public void virtual_collectVisibleElements_7517722170421689560(SNode thisNode, SNode ofType, List<SNode> res, boolean publicOnly);
}
