package de.voelter.mps.naming.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class NamespaceImport_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public NamespaceImport_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.naming.structure.NamespaceImport";
  }
}
