package de.voelter.mps.naming.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;
import java.util.List;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class Namespace_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements INamespaceContent_BehaviorDescriptor, INamespace_BehaviorDescriptor {
  public Namespace_BehaviorDescriptor() {
  }

  public String virtual_qualifiedName_5019556274771758840(SNode thisNode) {
    return IQualifiedNamedConcept_Behavior.virtual_qualifiedName_5019556274771758840(thisNode);
  }

  public SNode virtual_owningNamespace_5019556274771919323(SNode thisNode) {
    return INamespaceContent_Behavior.virtual_owningNamespace_5019556274771919323(thisNode);
  }

  public List<SNode> virtual_siblings_7517722170421689483(SNode thisNode) {
    return INamespace_Behavior.virtual_siblings_7517722170421689483(thisNode);
  }

  public List<SNode> virtual_allVisibleNode_7517722170421689521(SNode thisNode, SNode ofType) {
    return INamespace_Behavior.virtual_allVisibleNode_7517722170421689521(thisNode, ofType);
  }

  public boolean virtual_isExternallyVisible_5856418980158996214(SNode thisNode) {
    return INamespaceContent_Behavior.virtual_isExternallyVisible_5856418980158996214(thisNode);
  }

  public void virtual_collectVisibleElements_7517722170421689560(SNode thisNode, SNode ofType, List<SNode> res, boolean publicOnly) {
    INamespace_Behavior.virtual_collectVisibleElements_7517722170421689560(thisNode, ofType, res, publicOnly);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.naming.structure.Namespace";
  }
}
