package de.voelter.mps.naming.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class UniqueNamesConstraint_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public UniqueNamesConstraint_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "de.voelter.mps.naming.structure.UniqueNamesConstraint";
  }
}
