package relmapping_entities.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.ReferenceMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import entities.behavior.Attribute_Behavior;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ITranslator2;

public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_3423138233967798359(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SNodeOperations.getIndexInParent(SNodeOperations.getParent(_context.getNode()));
  }

  public static Object propertyMacro_GetPropertyValue_3423138233967790412(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return "getValueFor" + SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(_context.getNode()), "relmapping.structure.Table"), "name") + "_" + SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3423138233967788307(final IOperationContext operationContext, final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "Adapter";
  }

  public static Object referenceMacro_GetReferent_3423138233967798340(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "mapper", true), "relmapping_entities.structure.AttributeColMapping"), "attribute", false)), "entities.structure.Entity"), "name");
  }

  public static Object referenceMacro_GetReferent_3423138233967798375(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "mapper", true), "relmapping_entities.structure.AttributeColMapping"), "attribute", false)), "entities.structure.Entity"), "name");
  }

  public static Object referenceMacro_GetReferent_3423138233967798403(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return Attribute_Behavior.call_getterName_726639030028408915(SLinkOperations.getTarget(SNodeOperations.cast(SLinkOperations.getTarget(_context.getNode(), "mapper", true), "relmapping_entities.structure.AttributeColMapping"), "attribute", false));
  }

  public static Object referenceMacro_GetReferent_3423138233967788937(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name") + "BaseAdapter";
  }

  public static Iterable sourceNodesQuery_3423138233967790403(final IOperationContext operationContext, final SourceSubstituteMacroNodesContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "tables", true)).<SNode>translate(new ITranslator2<SNode, SNode>() {
      public Iterable<SNode> translate(SNode it) {
        return SLinkOperations.getTargets(it, "columns", true);
      }
    });
  }
}
