package pgm.test;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.util.plugin.run.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import junit.framework.Assert;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

@MPSLaunch
public class testSubtyping_Test extends BaseTransformationTest {
  @Test
  public void test_testReference() throws Throwable {
    this.initTest("/Users/markus/Documents/mps-demos/2-MPS-Language-Composition-Demos-neu/langcompdemo.mpr", "r:22d8ccc7-043f-4f96-bc66-c54cc9ce0f0a(pgm.test)");
    this.runTest("pgm.test.testSubtyping_Test$TestBody", "test_testReference", true);
  }

  @MPSLaunch
  public static class TestBody extends BaseTestBody {
    public void test_testReference() throws Exception {
      this.addNodeById("8045911181178687551");
      Assert.assertSame(SLinkOperations.getTarget(SNodeOperations.cast(this.getNodeById("8045911181178687572"), "de.voelter.mps.expressions.playground.structure.VarRef"), "var", false), SNodeOperations.cast(this.getNodeById("8045911181178687553"), "de.voelter.mps.expressions.playground.structure.Variable"));
    }
  }
}
