package entities.sandbox.sandbox;

/*Generated by MPS */


public abstract class CompanyDBBaseAdapter {
  public CompanyDBBaseAdapter() {
  }

  private void createTableDepartments() {
    StringBuilder sql = new StringBuilder();
    sql.append("create table " + "Departments" + "(");
    sql.append("" + "id" + " " + "number");
    sql.append(", " + "descr" + " " + "char");
    sql.append(")");
  }

  private void createTablePeople() {
    StringBuilder sql = new StringBuilder();
    sql.append("create table " + "People" + "(");
    sql.append("" + "id" + " " + "number");
    sql.append(", " + "name" + " " + "char");
    sql.append(", " + "role" + " " + "char");
    sql.append(", " + "isFreelancer" + " " + "char");
    sql.append(")");
  }

  public void createTables() {
    createTableDepartments();
    createTablePeople();
  }

  public void storeDepartments(Object applicationData) {
    StringBuilder sql = new StringBuilder();
    sql.append("insert into" + "Departments" + "(");
    sql.append("" + "id");
    sql.append(", " + "descr");
    sql.append(") values (");
    sql.append("" + "\"" + getValueForDepartments_id(applicationData) + "\"");
    sql.append(", " + "\"" + getValueForDepartments_descr(applicationData) + "\"");
    sql.append(")");
  }

  public void storePeople(Object applicationData) {
    StringBuilder sql = new StringBuilder();
    sql.append("insert into" + "People" + "(");
    sql.append("" + "id");
    sql.append(", " + "name");
    sql.append(", " + "role");
    sql.append(", " + "isFreelancer");
    sql.append(") values (");
    sql.append("" + "\"" + getValueForPeople_id(applicationData) + "\"");
    sql.append(", " + "\"" + getValueForPeople_name(applicationData) + "\"");
    sql.append(", " + "\"" + getValueForPeople_role(applicationData) + "\"");
    sql.append(", " + "\"" + getValueForPeople_isFreelancer(applicationData) + "\"");
    sql.append(")");
  }

  public abstract String getValueForDepartments_id(Object applicationData);

  public abstract String getValueForDepartments_descr(Object applicationData);

  public abstract String getValueForPeople_id(Object applicationData);

  public abstract String getValueForPeople_name(Object applicationData);

  public abstract String getValueForPeople_role(Object applicationData);

  public abstract String getValueForPeople_isFreelancer(Object applicationData);
}
