package entities.sandbox.sandbox;

/*Generated by MPS */


public class CompanyDBAdapter extends CompanyDBBaseAdapter {
  public CompanyDBAdapter() {
  }

  public String getValueForDepartments_id(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Department o = (Department) arr[0];
    String val = o.getId() + "";
    return val;
  }

  public String getValueForDepartments_descr(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Department o = (Department) arr[0];
    String val = o.getDescription() + "";
    return val;
  }

  public String getValueForPeople_id(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Department o = (Department) arr[1];
    String val = o.getId() + "";
    return val;
  }

  public String getValueForPeople_name(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Employee o = (Employee) arr[1];
    String val = o.getName() + "";
    return val;
  }

  public String getValueForPeople_role(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Employee o = (Employee) arr[1];
    String val = o.getRole() + "";
    return val;
  }

  public String getValueForPeople_isFreelancer(Object applicationData) {
    Object[] arr = (Object[]) applicationData;
    Employee o = (Employee) arr[1];
    String val = o.getFreelancer() + "";
    return val;
  }
}
