package entities.sandbox.sandbox;

/*Generated by MPS */

import rbac_rt.RbacContext;

public class RbacSpecEntities extends RbacContext {
  public RbacSpecEntities() {
  }

  public boolean currentUserHasWritePermission(String resId) {
    // generate some code here that checks based on 
    // users, groups and permission whether the right 
    // should be granted 
    return false;
  }
}
