package uispec_validation.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.typesystem.inference.EquationInfo;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_LenghtOf_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_LenghtOf_InferenceRule() {
  }

  public void applyRule(final SNode lenghtOf, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = SLinkOperations.getTarget(lenghtOf, "expr", true);
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:baae5d1a-3a66-410e-83a2-6f4942fbd071(uispec_validation.typesystem)", "814100379888684735", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:baae5d1a-3a66-410e-83a2-6f4942fbd071(uispec_validation.typesystem)", "814100379888684727", true), (SNode) SConceptOperations.createNewNode("entities.structure.StringType", null), _info_12389875345);
    }
    {
      SNode _nodeToCheck_1029348928467 = lenghtOf;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:baae5d1a-3a66-410e-83a2-6f4942fbd071(uispec_validation.typesystem)", "814100379888684749", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:baae5d1a-3a66-410e-83a2-6f4942fbd071(uispec_validation.typesystem)", "814100379888684746", true), (SNode) SConceptOperations.createNewNode("de.voelter.mps.expressions.structure.IntType", null), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "uispec_validation.structure.LenghtOf";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
