package de.voelter.mps.naming.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntention;
import jetbrains.mps.intentions.Intention;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.action.SNodeFactoryOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class addImport_Intention extends BaseIntention implements Intention {
  public addImport_Intention() {
  }

  public String getConcept() {
    return "de.voelter.mps.naming.structure.Namespace";
  }

  public boolean isParameterized() {
    return false;
  }

  public boolean isErrorIntention() {
    return false;
  }

  public boolean isAvailableInChildNodes() {
    return false;
  }

  public String getDescription(final SNode node, final EditorContext editorContext) {
    return "Add Namespace Import";
  }

  public void execute(final SNode node, final EditorContext editorContext) {
    SNode ni = SNodeFactoryOperations.createNewNode("de.voelter.mps.naming.structure.NamespaceImport", null);
    ListSequence.fromList(SLinkOperations.getTargets(node, "imports", true)).addElement(ni);
    editorContext.select(SLinkOperations.getTarget(ni, "namespace", false), "");
  }

  public String getLocationString() {
    return "de.voelter.mps.naming.intentions";
  }
}
