package de.voelter.mps.naming.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("de.voelter.mps.naming", "8e140b25-af36-4747-a45b-0c06e5c68bce"), SModelReference.fromString("r:69b340c9-4f37-478c-a1de-471bfc05b479(de.voelter.mps.naming.intentions)"));
  }

  public void init() {
    add(new addImport_Intention(), "1224145309708873070");
    add(new addUniqueNamesConstraint_Intention(), "5019556274771863796");
  }
}
