package de.voelter.mps.expressions.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.runtime.PropertyConstraintsDescriptor;
import java.util.HashMap;

public class BinaryExpression_Constraints extends BaseConstraintsDescriptor {
  public BinaryExpression_Constraints() {
    super("de.voelter.mps.expressions.structure.BinaryExpression");
  }

  @Override
  protected Map<String, PropertyConstraintsDescriptor> getNotDefaultProperties() {
    Map<String, PropertyConstraintsDescriptor> properties = new HashMap();
    return properties;
  }
}
