package jetbrains.mps.baselanguage.exprblocks.dataFlow;

/*Generated by MPS */

import jetbrains.mps.lang.dataFlow.DataFlowBuilders;
import jetbrains.mps.lang.dataFlow.DataFlowManager;

public class DFABuilders extends DataFlowBuilders {
  public void install(DataFlowManager manager) {
    manager.register("jetbrains.mps.baselanguage.exprblocks.structure.BlockExpression", new BlockExpression_DataFlow());
    manager.register("jetbrains.mps.baselanguage.exprblocks.structure.BlockExpressionYield", new BlockExpressionYield_DataFlow());
    manager.register("jetbrains.mps.baselanguage.exprblocks.structure.ExpressionBlock", new ExpressionBlock_DataFlow());
  }
}
