package uispec_validation.structure;

/*Generated by MPS */

import de.voelter.mps.expressions.structure.Expression;
import jetbrains.mps.smodel.SNode;
import entities.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class AttributeRefExpr extends Expression {
  public static final String concept = "uispec_validation.structure.AttributeRefExpr";
  public static final String ATTR = "attr";

  public AttributeRefExpr(SNode node) {
    super(node);
  }

  public Attribute getAttr() {
    return (Attribute) this.getReferent(Attribute.class, AttributeRefExpr.ATTR);
  }

  public void setAttr(Attribute node) {
    super.setReferent(AttributeRefExpr.ATTR, node);
  }

  public static AttributeRefExpr newInstance(SModel sm, boolean init) {
    return (AttributeRefExpr) SModelUtil_new.instantiateConceptDeclaration("uispec_validation.structure.AttributeRefExpr", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static AttributeRefExpr newInstance(SModel sm) {
    return AttributeRefExpr.newInstance(sm, false);
  }
}
