package uispec_validation.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.impl.CompiledConceptDescriptor;
import jetbrains.mps.smodel.runtime.interpreted.StructureAspectInterpreted;

public class StructureAspectDescriptor implements jetbrains.mps.smodel.runtime.StructureAspectDescriptor {
  private static String[] stringSwitchCases_1htk8d_a0a0a = new String[]{"uispec_validation.structure.AttributeRefExpr", "uispec_validation.structure.IsSetExpression", "uispec_validation.structure.LenghtOf", "uispec_validation.structure.ValidatedField"};

  public StructureAspectDescriptor() {
  }

  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0a, conceptFqName)) {
      case 0:
        return new CompiledConceptDescriptor("uispec_validation.structure.AttributeRefExpr", "de.voelter.mps.expressions.structure.Expression", false, new String[]{"de.voelter.mps.expressions.structure.Expression"}, new String[]{}, new String[]{"attr"});
      case 1:
        return new CompiledConceptDescriptor("uispec_validation.structure.IsSetExpression", "de.voelter.mps.expressions.structure.Expression", false, new String[]{"de.voelter.mps.expressions.structure.Expression"}, new String[]{}, new String[]{});
      case 2:
        return new CompiledConceptDescriptor("uispec_validation.structure.LenghtOf", "de.voelter.mps.expressions.structure.Expression", false, new String[]{"de.voelter.mps.expressions.structure.Expression"}, new String[]{}, new String[]{});
      case 3:
        return new CompiledConceptDescriptor("uispec_validation.structure.ValidatedField", "uispec.structure.Field", false, new String[]{"uispec.structure.Field"}, new String[]{}, new String[]{});
      default:
        return StructureAspectInterpreted.getInstance().getDescriptor(conceptFqName);
    }
  }
}
