package simplecalc.behavior;

/*Generated by MPS */

import de.voelter.mps.expressions.behavior.BinaryExpression_BehaviorDescriptor;

public class ANdOP_BehaviorDescriptor extends BinaryExpression_BehaviorDescriptor {
  public ANdOP_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.ANdOP";
  }
}
