package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class DocText_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public DocText_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.DocText";
  }
}
