package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;

public class StructType_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode virtual_dotExpressionConcept_5856418980158943574(SNode thisNode) {
    return SConceptOperations.findConceptDeclaration("simplecalc.structure.MyOwnDotExpression");
  }
}
