package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import de.voelter.mps.expressions.behavior.IMemberReference_BehaviorDescriptor;

public class StructMemberAccess_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements IMemberReference_BehaviorDescriptor {
  public StructMemberAccess_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.StructMemberAccess";
  }
}
