package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class System_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public System_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.System";
  }
}
