package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class VarDecl_BehaviorDescriptor extends SysContent_BehaviorDescriptor implements INamedConcept_BehaviorDescriptor {
  public VarDecl_BehaviorDescriptor() {
  }

  public boolean virtual_isExternallyVisible_5856418980158996214(SNode thisNode) {
    return VarDecl_Behavior.virtual_isExternallyVisible_5856418980158996214(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.VarDecl";
  }
}
