package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class VarDecl_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean virtual_isExternallyVisible_5856418980158996214(SNode thisNode) {
    return SPropertyOperations.getBoolean(thisNode, "isPublic");
  }
}
