package simplecalc.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class VarRefExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_toText_5815279313395675462(SNode thisNode) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(thisNode, "var", false), "name");
  }
}
