package simplecalc.behavior;

/*Generated by MPS */

import de.voelter.mps.expressions.behavior.Expression_BehaviorDescriptor;
import de.voelter.mps.expressions.behavior.ISimpleText_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class VarRefExpression_BehaviorDescriptor extends Expression_BehaviorDescriptor implements ISimpleText_BehaviorDescriptor {
  public VarRefExpression_BehaviorDescriptor() {
  }

  public String virtual_toText_5815279313395675462(SNode thisNode) {
    return VarRefExpression_Behavior.virtual_toText_5815279313395675462(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "simplecalc.structure.VarRefExpression";
  }
}
