package jetbrains.mps.baselanguage.exprblocks.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;

public class ExpressionBlock_Constraints extends BaseConstraintsDescriptor {
  public ExpressionBlock_Constraints() {
    super("jetbrains.mps.baselanguage.exprblocks.structure.ExpressionBlock");
  }
}
