package de.voelter.mps.textshape.structure;

/*Generated by MPS */


public class BlankLineBeforeAnn_AnnotationLink {
  public static final String BLANK_LINE_BEFORE_ANN = "blankLineBeforeAnn";

  public static void setBlankLineBeforeAnn(IFileContent source, NeedsBlankLink target) {
    source.setAttribute(BlankLineBeforeAnn_AnnotationLink.BLANK_LINE_BEFORE_ANN, target);
  }

  public static NeedsBlankLink getBlankLineBeforeAnn(IFileContent source) {
    return (NeedsBlankLink) source.getAttribute(BlankLineBeforeAnn_AnnotationLink.BLANK_LINE_BEFORE_ANN);
  }
}
