package de.voelter.mps.textshape.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IStatement extends INodeAdapter {
  public static final String concept = "de.voelter.mps.textshape.structure.IStatement";
}
