package de.voelter.mps.textshape.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class PascalDeclaration extends BaseConcept implements IFileContent, IStatement {
  public static final String concept = "de.voelter.mps.textshape.structure.PascalDeclaration";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String QUALIFIERS = "qualifiers";
  public static final String TYPE = "type";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public PascalDeclaration(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(PascalDeclaration.NAME);
  }

  public void setName(String value) {
    this.setProperty(PascalDeclaration.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(PascalDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(PascalDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(PascalDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(PascalDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(PascalDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(PascalDeclaration.VIRTUAL_PACKAGE, value);
  }

  public MultiTextToken getQualifiers() {
    return (MultiTextToken) this.getChild(MultiTextToken.class, PascalDeclaration.QUALIFIERS);
  }

  public void setQualifiers(MultiTextToken node) {
    super.setChild(PascalDeclaration.QUALIFIERS, node);
  }

  public SingleTextToken getType() {
    return (SingleTextToken) this.getChild(SingleTextToken.class, PascalDeclaration.TYPE);
  }

  public void setType(SingleTextToken node) {
    super.setChild(PascalDeclaration.TYPE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(PascalDeclaration.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, PascalDeclaration.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, PascalDeclaration.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(PascalDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, PascalDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public static PascalDeclaration newInstance(SModel sm, boolean init) {
    return (PascalDeclaration) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.textshape.structure.PascalDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static PascalDeclaration newInstance(SModel sm) {
    return PascalDeclaration.newInstance(sm, false);
  }
}
