package simplecalc.constraints;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.base.BaseConstraintsDescriptor;
import jetbrains.mps.smodel.SNodePointer;
import java.util.Map;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsDescriptor;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.base.BaseReferenceConstraintsDescriptor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.runtime.ReferenceScopeProvider;
import jetbrains.mps.smodel.runtime.base.BaseReferenceScopeProvider;
import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.smodel.runtime.ReferenceConstraintsContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import de.voelter.mps.naming.behavior.INamespace_Behavior;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.internal.collections.runtime.ISelector;

public class VarRefExpression_Constraints extends BaseConstraintsDescriptor {
  private static SNodePointer breakingNode_47u1ot_a0a1a0a0a1a0b0a1a0 = new SNodePointer("r:ea2f0d5b-629e-46e6-b033-73702cbe9ef7(simplecalc.constraints)", "5019556274771920110");

  public VarRefExpression_Constraints() {
    super("simplecalc.structure.VarRefExpression");
  }

  @Override
  protected Map<String, ReferenceConstraintsDescriptor> getNotDefaultReferences() {
    Map<String, ReferenceConstraintsDescriptor> references = new HashMap();
    references.put("var", new BaseReferenceConstraintsDescriptor("var", this) {
      @Override
      public boolean hasOwnScopeProvider() {
        return true;
      }

      @Nullable
      @Override
      public ReferenceScopeProvider getScopeProvider() {
        return new BaseReferenceScopeProvider() {
          @Override
          public Object createSearchScopeOrListOfNodes(final IOperationContext operationContext, final ReferenceConstraintsContext _context) {
            return ListSequence.fromList(INamespace_Behavior.call_allVisibleNode_7517722170421689521(SNodeOperations.getAncestor(_context.getEnclosingNode(), "de.voelter.mps.naming.structure.Namespace", true, false), SConceptOperations.findConceptDeclaration("simplecalc.structure.VarDecl"))).<SNode>select(new ISelector<SNode, SNode>() {
              public SNode select(SNode it) {
                return SNodeOperations.cast(it, "simplecalc.structure.VarDecl");
              }
            });
          }

          @Override
          public SNodePointer getSearchScopeValidatorNode() {
            return breakingNode_47u1ot_a0a1a0a0a1a0b0a1a0;
          }
        };
      }
    });
    return references;
  }
}
