package rbac_entities.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.smodel.IOperationContext;
import jetbrains.mps.generator.template.BaseMappingRuleContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.baselanguage.exprblocks.behavior.PlaceholderStatement_Behavior;
import jetbrains.mps.generator.template.ReferenceMacroContext;

public class QueriesGenerated {
  public static boolean baseMappingRule_Condition_3423138233967802647(final IOperationContext operationContext, final BaseMappingRuleContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name").equals("pre-set");
  }

  public static Object propertyMacro_GetPropertyValue_4808699962363378435(final IOperationContext operationContext, final PropertyMacroContext _context) {
    SNode attr = SNodeOperations.cast(PlaceholderStatement_Behavior.call_getData_5359815737040877621(_context.getNode(), _context), "entities.structure.Attribute");
    return SPropertyOperations.getString(SNodeOperations.cast(SNodeOperations.getParent(attr), "entities.structure.Entity"), "name") + "." + SPropertyOperations.getString(attr, "name");
  }

  public static Object referenceMacro_GetReferent_4808699962363376977(final IOperationContext operationContext, final ReferenceMacroContext _context) {
    return "RbacSpecEntities";
  }
}
