package relmapping_annotations.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("relmapping_annotations", "1ad2994d-cbd8-42a7-87d3-8f58334a0471"), SModelReference.fromString("r:88c1fca6-da3b-414c-86da-45540f7a1a18(relmapping_annotations.intentions)"));
  }

  public void init() {
    add(new toggleColMapping_Intention(), "4808699962363388635");
  }
}
