package relmapping_entities.behavior;

/*Generated by MPS */

import relmapping.behavior.ColumnMapper_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public class AttributeColMapping_BehaviorDescriptor extends ColumnMapper_BehaviorDescriptor {
  public AttributeColMapping_BehaviorDescriptor() {
  }

  public SNode virtual_typeMappedToDB_726639030028562152(SNode thisNode) {
    return AttributeColMapping_Behavior.virtual_typeMappedToDB_726639030028562152(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "relmapping_entities.structure.AttributeColMapping";
  }
}
