package uispec.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ComboWidget extends Widget {
  public static final String concept = "uispec.structure.ComboWidget";
  public static final String VALUES = "values";

  public ComboWidget(SNode node) {
    super(node);
  }

  public int getValuesesCount() {
    return this.getChildCount(ComboWidget.VALUES);
  }

  public Iterator<ComboValue> valueses() {
    return this.children(ComboValue.class, ComboWidget.VALUES);
  }

  public List<ComboValue> getValueses() {
    return this.getChildren(ComboValue.class, ComboWidget.VALUES);
  }

  public void addValues(ComboValue node) {
    this.addChild(ComboWidget.VALUES, node);
  }

  public void insertValues(ComboValue prev, ComboValue node) {
    this.insertChild(prev, ComboWidget.VALUES, node);
  }

  public static ComboWidget newInstance(SModel sm, boolean init) {
    return (ComboWidget) SModelUtil_new.instantiateConceptDeclaration("uispec.structure.ComboWidget", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ComboWidget newInstance(SModel sm) {
    return ComboWidget.newInstance(sm, false);
  }
}
