package uispec.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ComboValue extends BaseConcept {
  public static final String concept = "uispec.structure.ComboValue";
  public static final String VALUE = "value";

  public ComboValue(SNode node) {
    super(node);
  }

  public String getValue() {
    return this.getProperty(ComboValue.VALUE);
  }

  public void setValue(String value) {
    this.setProperty(ComboValue.VALUE, value);
  }

  public static ComboValue newInstance(SModel sm, boolean init) {
    return (ComboValue) SModelUtil_new.instantiateConceptDeclaration("uispec.structure.ComboValue", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ComboValue newInstance(SModel sm) {
    return ComboValue.newInstance(sm, false);
  }
}
