package uispec.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class TextFieldWidget extends Widget {
  public static final String concept = "uispec.structure.TextFieldWidget";
  public static final String LENGTH = "length";

  public TextFieldWidget(SNode node) {
    super(node);
  }

  public int getLength() {
    return this.getIntegerProperty(TextFieldWidget.LENGTH);
  }

  public void setLength(int value) {
    this.setIntegerProperty(TextFieldWidget.LENGTH, value);
  }

  public static TextFieldWidget newInstance(SModel sm, boolean init) {
    return (TextFieldWidget) SModelUtil_new.instantiateConceptDeclaration("uispec.structure.TextFieldWidget", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static TextFieldWidget newInstance(SModel sm) {
    return TextFieldWidget.newInstance(sm, false);
  }
}
