package uispec.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Uispec_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("17b9debb-99e7-40c9-bb9d-23a28b0a7c10(uispec)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
