package entities.sandbox.sandbox;

/*Generated by MPS */


public class Department {
  private int id;
  private String description;

  public Department() {
  }

  public void setId(int newValue) {
    // check permissions (from rbac_entities) 
    if (new RbacSpecEntities().currentUserHasWritePermission("Department.id")) {
      throw new RuntimeException("no permission");
    }
    this.id = newValue;
  }

  public void setDescription(String newValue) {
    // check permissions (from rbac_entities) 
    if (new RbacSpecEntities().currentUserHasWritePermission("Department.description")) {
      throw new RuntimeException("no permission");
    }
    this.description = newValue;
  }

  public int getId() {
    return id;
  }

  public String getDescription() {
    return description;
  }

  public String toString() {
    StringBuilder bf = new StringBuilder();
    bf.append("Department" + "\n");
    bf.append("  " + "id" + ":" + getId() + "\n");
    bf.append("  " + "description" + ":" + getDescription() + "\n");
    return bf.toString();
  }
}
