package entities.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"entities.structure.Attribute", "entities.structure.EBooleanType", "entities.structure.EIntType", "entities.structure.EStringType", "entities.structure.Entity", "entities.structure.EntityType", "entities.structure.Module"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 6:
        return new Module_BehaviorDescriptor();
      case 4:
        return new Entity_BehaviorDescriptor();
      case 0:
        return new Attribute_BehaviorDescriptor();
      case 2:
        return new EIntType_BehaviorDescriptor();
      case 3:
        return new EStringType_BehaviorDescriptor();
      case 5:
        return new EntityType_BehaviorDescriptor();
      case 1:
        return new EBooleanType_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
