package entities.behavior;

/*Generated by MPS */


public class EStringType_BehaviorDescriptor extends Type_BehaviorDescriptor {
  public EStringType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "entities.structure.EStringType";
  }
}
