package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class BinaryArithmeticExpression extends BinaryExpression {
  public static final String concept = "de.voelter.mps.expressions.structure.BinaryArithmeticExpression";

  public BinaryArithmeticExpression(SNode node) {
    super(node);
  }

  public static BinaryArithmeticExpression newInstance(SModel sm, boolean init) {
    return (BinaryArithmeticExpression) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.BinaryArithmeticExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static BinaryArithmeticExpression newInstance(SModel sm) {
    return BinaryArithmeticExpression.newInstance(sm, false);
  }
}
