package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EqualsExpression extends BinaryComparisonExpression {
  public static final String concept = "de.voelter.mps.expressions.structure.EqualsExpression";

  public EqualsExpression(SNode node) {
    super(node);
  }

  public static EqualsExpression newInstance(SModel sm, boolean init) {
    return (EqualsExpression) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.EqualsExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EqualsExpression newInstance(SModel sm) {
    return EqualsExpression.newInstance(sm, false);
  }
}
