package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Expressions_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("61c69711-ed61-4850-81d9-7714ff227fb0(de.voelter.mps.expressions)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
