package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class FalseLiteral extends BooleanLiteral {
  public static final String concept = "de.voelter.mps.expressions.structure.FalseLiteral";

  public FalseLiteral(SNode node) {
    super(node);
  }

  public static FalseLiteral newInstance(SModel sm, boolean init) {
    return (FalseLiteral) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.FalseLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static FalseLiteral newInstance(SModel sm) {
    return FalseLiteral.newInstance(sm, false);
  }
}
