package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class GreaterExpression extends BinaryComparisonExpression {
  public static final String concept = "de.voelter.mps.expressions.structure.GreaterExpression";

  public GreaterExpression(SNode node) {
    super(node);
  }

  public static GreaterExpression newInstance(SModel sm, boolean init) {
    return (GreaterExpression) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.GreaterExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static GreaterExpression newInstance(SModel sm) {
    return GreaterExpression.newInstance(sm, false);
  }
}
