package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IDotExpression extends INodeAdapter {
  public static final String concept = "de.voelter.mps.expressions.structure.IDotExpression";
  public static final String CONTEXT = "context";

  public Expression getContext();
  public void setContext(Expression node);
}
