package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface IMemberReference extends INodeAdapter {
  public static final String concept = "de.voelter.mps.expressions.structure.IMemberReference";
}
