package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class IntegerLiteral extends Literal {
  public static final String concept = "de.voelter.mps.expressions.structure.IntegerLiteral";
  public static final String VALUE = "value";

  public IntegerLiteral(SNode node) {
    super(node);
  }

  public int getValue() {
    return this.getIntegerProperty(IntegerLiteral.VALUE);
  }

  public void setValue(int value) {
    this.setIntegerProperty(IntegerLiteral.VALUE, value);
  }

  public static IntegerLiteral newInstance(SModel sm, boolean init) {
    return (IntegerLiteral) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.IntegerLiteral", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static IntegerLiteral newInstance(SModel sm) {
    return IntegerLiteral.newInstance(sm, false);
  }
}
