package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ParensExpression extends Expression {
  public static final String concept = "de.voelter.mps.expressions.structure.ParensExpression";
  public static final String EXPR = "expr";

  public ParensExpression(SNode node) {
    super(node);
  }

  public Expression getExpr() {
    return (Expression) this.getChild(Expression.class, ParensExpression.EXPR);
  }

  public void setExpr(Expression node) {
    super.setChild(ParensExpression.EXPR, node);
  }

  public static ParensExpression newInstance(SModel sm, boolean init) {
    return (ParensExpression) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.ParensExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ParensExpression newInstance(SModel sm) {
    return ParensExpression.newInstance(sm, false);
  }
}
