package de.voelter.mps.expressions.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Type extends BaseConcept {
  public static final String concept = "de.voelter.mps.expressions.structure.Type";

  public Type(SNode node) {
    super(node);
  }

  public static Type newInstance(SModel sm, boolean init) {
    return (Type) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.expressions.structure.Type", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Type newInstance(SModel sm) {
    return Type.newInstance(sm, false);
  }
}
