package de.voelter.mps.naming.structure;

/*Generated by MPS */


public interface INamespaceContent extends IQualifiedNamedConcept {
  public static final String concept = "de.voelter.mps.naming.structure.INamespaceContent";
}
