package de.voelter.mps.naming.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;

public interface IQualifiedNamedConcept extends INamedConcept {
  public static final String concept = "de.voelter.mps.naming.structure.IQualifiedNamedConcept";
}
