package de.voelter.mps.naming.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class NamespaceImport extends BaseConcept {
  public static final String concept = "de.voelter.mps.naming.structure.NamespaceImport";
  public static final String NAMESPACE = "namespace";

  public NamespaceImport(SNode node) {
    super(node);
  }

  public Namespace getNamespace() {
    return (Namespace) this.getReferent(Namespace.class, NamespaceImport.NAMESPACE);
  }

  public void setNamespace(Namespace node) {
    super.setReferent(NamespaceImport.NAMESPACE, node);
  }

  public static NamespaceImport newInstance(SModel sm, boolean init) {
    return (NamespaceImport) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.naming.structure.NamespaceImport", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static NamespaceImport newInstance(SModel sm) {
    return NamespaceImport.newInstance(sm, false);
  }
}
