package de.voelter.mps.naming.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Naming_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("8e140b25-af36-4747-a45b-0c06e5c68bce(de.voelter.mps.naming)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
