package de.voelter.mps.naming.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class UniqueNamesConstraint extends BaseConcept {
  public static final String concept = "de.voelter.mps.naming.structure.UniqueNamesConstraint";

  public UniqueNamesConstraint(SNode node) {
    super(node);
  }

  public static UniqueNamesConstraint newInstance(SModel sm, boolean init) {
    return (UniqueNamesConstraint) SModelUtil_new.instantiateConceptDeclaration("de.voelter.mps.naming.structure.UniqueNamesConstraint", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static UniqueNamesConstraint newInstance(SModel sm) {
    return UniqueNamesConstraint.newInstance(sm, false);
  }
}
