package relmapping_annotations.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Relmapping_annotations_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("1ad2994d-cbd8-42a7-87d3-8f58334a0471(relmapping_annotations)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
