package jetbrains.mps.baselanguage.exprblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"jetbrains.mps.baselanguage.exprblocks.structure.BlockExpression", "jetbrains.mps.baselanguage.exprblocks.structure.BlockExpressionYield", "jetbrains.mps.baselanguage.exprblocks.structure.ExpressionBlock", "jetbrains.mps.baselanguage.exprblocks.structure.ExpressionBlockExprRef", "jetbrains.mps.baselanguage.exprblocks.structure.PlaceholderStatement", "jetbrains.mps.baselanguage.exprblocks.structure.TransparentBlock"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 2:
        return new ExpressionBlock_BehaviorDescriptor();
      case 3:
        return new ExpressionBlockExprRef_BehaviorDescriptor();
      case 0:
        return new BlockExpression_BehaviorDescriptor();
      case 1:
        return new BlockExpressionYield_BehaviorDescriptor();
      case 4:
        return new PlaceholderStatement_BehaviorDescriptor();
      case 5:
        return new TransparentBlock_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
