package jetbrains.mps.baselanguage.exprblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.generator.template.TemplateQueryContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class PlaceholderStatement_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode call_getData_5359815737040877621(SNode thisNode, TemplateQueryContext ctx) {
    return (SNode) ctx.getSessionObject(SPropertyOperations.getString(thisNode, "key"));
  }

  public static void call_setData_5359815737040879073(SNode thisNode, TemplateQueryContext ctx, SNode data) {
    ctx.putSessionObject(SPropertyOperations.getString(thisNode, "key"), data);
  }
}
