package jetbrains.mps.baselanguage.exprblocks.behavior;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.behavior.Statement_BehaviorDescriptor;

public class TransparentBlock_BehaviorDescriptor extends Statement_BehaviorDescriptor {
  public TransparentBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.baselanguage.exprblocks.structure.TransparentBlock";
  }
}
