package de.voelter.mps.gv.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class DiagramAnnotation_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "sep", "0.1");
  }
}
