package relmapping.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BehaviorDescriptor;
import java.util.Arrays;
import jetbrains.mps.smodel.runtime.interpreted.BehaviorAspectInterpreted;

public class BehaviorAspectDescriptor implements jetbrains.mps.smodel.runtime.BehaviorAspectDescriptor {
  private static String[] stringSwitchCases_846f5o_a0a0a = new String[]{"relmapping.structure.CharType", "relmapping.structure.Column", "relmapping.structure.Database", "relmapping.structure.NumberType", "relmapping.structure.Table"};

  public BehaviorAspectDescriptor() {
  }

  public BehaviorDescriptor getDescriptor(String fqName) {
    switch (Arrays.binarySearch(stringSwitchCases_846f5o_a0a0a, fqName)) {
      case 2:
        return new Database_BehaviorDescriptor();
      case 4:
        return new Table_BehaviorDescriptor();
      case 1:
        return new Column_BehaviorDescriptor();
      case 0:
        return new CharType_BehaviorDescriptor();
      case 3:
        return new NumberType_BehaviorDescriptor();
      default:
        return BehaviorAspectInterpreted.getInstance().getDescriptor(fqName);
    }
  }
}
