package relmapping.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import jetbrains.mps.smodel.SNode;

public abstract class ColumnMapper_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public ColumnMapper_BehaviorDescriptor() {
  }

  public SNode virtual_typeMappedToDB_726639030028562152(SNode thisNode) {
    return ColumnMapper_Behavior.virtual_typeMappedToDB_726639030028562152(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "relmapping.structure.ColumnMapper";
  }
}
