package relmapping.behavior;

/*Generated by MPS */


public class NumberType_BehaviorDescriptor extends DataType_BehaviorDescriptor {
  public NumberType_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "relmapping.structure.NumberType";
  }
}
