package relmapping.typesystem;

/*Generated by MPS */

import jetbrains.mps.lang.typesystem.runtime.AbstractInferenceRule_Runtime;
import jetbrains.mps.lang.typesystem.runtime.InferenceRule_Runtime;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.typesystem.inference.TypeCheckingContext;
import jetbrains.mps.lang.typesystem.runtime.IsApplicableStatus;
import jetbrains.mps.typesystem.inference.EquationInfo;
import relmapping.behavior.ColumnMapper_Behavior;
import jetbrains.mps.smodel.SModelUtil_new;

public class typeof_ColumnMapper_InferenceRule extends AbstractInferenceRule_Runtime implements InferenceRule_Runtime {
  public typeof_ColumnMapper_InferenceRule() {
  }

  public void applyRule(final SNode columnMapper, final TypeCheckingContext typeCheckingContext, IsApplicableStatus status) {
    {
      SNode _nodeToCheck_1029348928467 = columnMapper;
      EquationInfo _info_12389875345 = new EquationInfo(_nodeToCheck_1029348928467, null, "r:f74a9ed4-db9e-429e-9ba7-6b24af5293dc(relmapping.typesystem)", "726639030028565012", 0, null);
      typeCheckingContext.createEquation((SNode) typeCheckingContext.typeOf(_nodeToCheck_1029348928467, "r:f74a9ed4-db9e-429e-9ba7-6b24af5293dc(relmapping.typesystem)", "726639030028565009", true), (SNode) ColumnMapper_Behavior.call_typeMappedToDB_726639030028562152(columnMapper), _info_12389875345);
    }
  }

  public String getApplicableConceptFQName() {
    return "relmapping.structure.ColumnMapper";
  }

  public IsApplicableStatus isApplicableAndPattern(SNode argument) {
    {
      boolean b = SModelUtil_new.isAssignableConcept(argument.getConceptFqName(), this.getApplicableConceptFQName());
      return new IsApplicableStatus(b, null);
    }
  }

  public boolean overrides() {
    return false;
  }
}
