package simplecalc.structure;

/*Generated by MPS */

import de.voelter.mps.expressions.structure.BinaryExpression;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class ANdOP extends BinaryExpression {
  public static final String concept = "simplecalc.structure.ANdOP";

  public ANdOP(SNode node) {
    super(node);
  }

  public static ANdOP newInstance(SModel sm, boolean init) {
    return (ANdOP) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.ANdOP", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static ANdOP newInstance(SModel sm) {
    return ANdOP.newInstance(sm, false);
  }
}
