package simplecalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;

public class Doc_AnnotationLink {
  public static final String DOC = "doc";

  public static void setDoc(BaseConcept source, DocText target) {
    source.setAttribute(Doc_AnnotationLink.DOC, target);
  }

  public static DocText getDoc(BaseConcept source) {
    return (DocText) source.getAttribute(Doc_AnnotationLink.DOC);
  }
}
