package simplecalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class DocText extends BaseConcept {
  public static final String concept = "simplecalc.structure.DocText";
  public static final String TEXT = "text";

  public DocText(SNode node) {
    super(node);
  }

  public String getText() {
    return this.getProperty(DocText.TEXT);
  }

  public void setText(String value) {
    this.setProperty(DocText.TEXT, value);
  }

  public static DocText newInstance(SModel sm, boolean init) {
    return (DocText) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.DocText", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static DocText newInstance(SModel sm) {
    return DocText.newInstance(sm, false);
  }
}
