package simplecalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import de.voelter.mps.expressions.structure.Type;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructMember extends BaseConcept implements INamedConcept {
  public static final String concept = "simplecalc.structure.StructMember";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String TYPE = "type";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public StructMember(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(StructMember.NAME);
  }

  public void setName(String value) {
    this.setProperty(StructMember.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(StructMember.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(StructMember.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(StructMember.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(StructMember.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(StructMember.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(StructMember.VIRTUAL_PACKAGE, value);
  }

  public Type getType() {
    return (Type) this.getChild(Type.class, StructMember.TYPE);
  }

  public void setType(Type node) {
    super.setChild(StructMember.TYPE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(StructMember.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, StructMember.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, StructMember.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(StructMember.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, StructMember.SMODEL_ATTRIBUTE, node);
  }

  public static StructMember newInstance(SModel sm, boolean init) {
    return (StructMember) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.StructMember", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructMember newInstance(SModel sm) {
    return StructMember.newInstance(sm, false);
  }
}
