package simplecalc.structure;

/*Generated by MPS */

import de.voelter.mps.expressions.structure.Type;
import de.voelter.mps.expressions.structure.IMemberContainer;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructType extends Type implements IMemberContainer {
  public static final String concept = "simplecalc.structure.StructType";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String STRUCT = "struct";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public StructType(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(StructType.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(StructType.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(StructType.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(StructType.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(StructType.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(StructType.VIRTUAL_PACKAGE, value);
  }

  public Struct getStruct() {
    return (Struct) this.getReferent(Struct.class, StructType.STRUCT);
  }

  public void setStruct(Struct node) {
    super.setReferent(StructType.STRUCT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(StructType.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, StructType.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, StructType.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(StructType.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, StructType.SMODEL_ATTRIBUTE, node);
  }

  public static StructType newInstance(SModel sm, boolean init) {
    return (StructType) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.StructType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructType newInstance(SModel sm) {
    return StructType.newInstance(sm, false);
  }
}
