package simplecalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import de.voelter.mps.expressions.structure.IMemberReference;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructMemberAccess extends BaseConcept implements IMemberReference {
  public static final String concept = "simplecalc.structure.StructMemberAccess";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String MEMBER = "member";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public StructMemberAccess(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(StructMemberAccess.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(StructMemberAccess.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(StructMemberAccess.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(StructMemberAccess.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(StructMemberAccess.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(StructMemberAccess.VIRTUAL_PACKAGE, value);
  }

  public StructMember getMember() {
    return (StructMember) this.getReferent(StructMember.class, StructMemberAccess.MEMBER);
  }

  public void setMember(StructMember node) {
    super.setReferent(StructMemberAccess.MEMBER, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(StructMemberAccess.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, StructMemberAccess.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, StructMemberAccess.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(StructMemberAccess.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, StructMemberAccess.SMODEL_ATTRIBUTE, node);
  }

  public static StructMemberAccess newInstance(SModel sm, boolean init) {
    return (StructMemberAccess) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.StructMemberAccess", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructMemberAccess newInstance(SModel sm) {
    return StructMemberAccess.newInstance(sm, false);
  }
}
