package simplecalc.structure;

/*Generated by MPS */

import de.voelter.mps.expressions.structure.Expression;
import de.voelter.mps.expressions.structure.ISimpleText;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class StructRefExpression extends Expression implements ISimpleText {
  public static final String concept = "simplecalc.structure.StructRefExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String STRUCT = "struct";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public StructRefExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(StructRefExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(StructRefExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(StructRefExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(StructRefExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(StructRefExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(StructRefExpression.VIRTUAL_PACKAGE, value);
  }

  public Struct getStruct() {
    return (Struct) this.getReferent(Struct.class, StructRefExpression.STRUCT);
  }

  public void setStruct(Struct node) {
    super.setReferent(StructRefExpression.STRUCT, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(StructRefExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, StructRefExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, StructRefExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(StructRefExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, StructRefExpression.SMODEL_ATTRIBUTE, node);
  }

  public static StructRefExpression newInstance(SModel sm, boolean init) {
    return (StructRefExpression) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.StructRefExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static StructRefExpression newInstance(SModel sm) {
    return StructRefExpression.newInstance(sm, false);
  }
}
