package simplecalc.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import de.voelter.mps.expressions.structure.Type;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class VarDecl extends SysContent implements INamedConcept {
  public static final String concept = "simplecalc.structure.VarDecl";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String IS_PUBLIC = "isPublic";
  public static final String TYPE = "type";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public VarDecl(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(VarDecl.NAME);
  }

  public void setName(String value) {
    this.setProperty(VarDecl.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(VarDecl.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(VarDecl.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(VarDecl.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(VarDecl.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(VarDecl.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(VarDecl.VIRTUAL_PACKAGE, value);
  }

  public boolean getIsPublic() {
    return this.getBooleanProperty(VarDecl.IS_PUBLIC);
  }

  public void setIsPublic(boolean value) {
    this.setBooleanProperty(VarDecl.IS_PUBLIC, value);
  }

  public Type getType() {
    return (Type) this.getChild(Type.class, VarDecl.TYPE);
  }

  public void setType(Type node) {
    super.setChild(VarDecl.TYPE, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(VarDecl.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, VarDecl.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, VarDecl.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(VarDecl.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, VarDecl.SMODEL_ATTRIBUTE, node);
  }

  public static VarDecl newInstance(SModel sm, boolean init) {
    return (VarDecl) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.VarDecl", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static VarDecl newInstance(SModel sm) {
    return VarDecl.newInstance(sm, false);
  }
}
