package simplecalc.structure;

/*Generated by MPS */

import de.voelter.mps.expressions.structure.Expression;
import de.voelter.mps.expressions.structure.ISimpleText;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class VarRefExpression extends Expression implements ISimpleText {
  public static final String concept = "simplecalc.structure.VarRefExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String VAR = "var";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public VarRefExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(VarRefExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(VarRefExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(VarRefExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(VarRefExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(VarRefExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(VarRefExpression.VIRTUAL_PACKAGE, value);
  }

  public VarDecl getVar() {
    return (VarDecl) this.getReferent(VarDecl.class, VarRefExpression.VAR);
  }

  public void setVar(VarDecl node) {
    super.setReferent(VarRefExpression.VAR, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(VarRefExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, VarRefExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, VarRefExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(VarRefExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, VarRefExpression.SMODEL_ATTRIBUTE, node);
  }

  public static VarRefExpression newInstance(SModel sm, boolean init) {
    return (VarRefExpression) SModelUtil_new.instantiateConceptDeclaration("simplecalc.structure.VarRefExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static VarRefExpression newInstance(SModel sm) {
    return VarRefExpression.newInstance(sm, false);
  }
}
