package uispec_validation.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("uispec_validation", "9c6246ba-6b2a-4549-885e-5dc2539e924f"), SModelReference.fromString("r:89df9415-b654-4309-a96c-accb60bb5998(uispec_validation.intentions)"));
  }

  public void init() {
    add(new makeValidated_Intention(), "814100379888667828");
  }
}
