package rbac_rt;

/*Generated by MPS */


public abstract class RbacContext {
  private static ThreadLocal curUser = new ThreadLocal();

  public RbacContext() {
  }

  public boolean currentUserHasWritePermission(String resId) {
    return false;
  }

  public String getCurUserId() {
    return (String) curUser.get();
  }
}
