package entities.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class BooleanType extends Type {
  public static final String concept = "entities.structure.BooleanType";

  public BooleanType(SNode node) {
    super(node);
  }

  public static BooleanType newInstance(SModel sm, boolean init) {
    return (BooleanType) SModelUtil_new.instantiateConceptDeclaration("entities.structure.BooleanType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static BooleanType newInstance(SModel sm) {
    return BooleanType.newInstance(sm, false);
  }
}
