package entities.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Entities_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("35d965b5-81f3-4b69-8efc-9827152f5513(entities)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
