package entities.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class EStringType extends Type {
  public static final String concept = "entities.structure.EStringType";

  public EStringType(SNode node) {
    super(node);
  }

  public static EStringType newInstance(SModel sm, boolean init) {
    return (EStringType) SModelUtil_new.instantiateConceptDeclaration("entities.structure.EStringType", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static EStringType newInstance(SModel sm) {
    return EStringType.newInstance(sm, false);
  }
}
