package entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import java.util.List;
import jetbrains.mps.lang.core.structure.Attribute;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class Module extends BaseConcept implements INamedConcept {
  public static final String concept = "entities.structure.Module";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String ENTITIES = "entities";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public Module(SNode node) {
    super(node);
  }

  public String getName() {
    return this.getProperty(Module.NAME);
  }

  public void setName(String value) {
    this.setProperty(Module.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(Module.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(Module.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(Module.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(Module.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(Module.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(Module.VIRTUAL_PACKAGE, value);
  }

  public int getEntitiesesCount() {
    return this.getChildCount(Module.ENTITIES);
  }

  public Iterator<Entity> entitieses() {
    return this.children(Entity.class, Module.ENTITIES);
  }

  public List<Entity> getEntitieses() {
    return this.getChildren(Entity.class, Module.ENTITIES);
  }

  public void addEntities(Entity node) {
    this.addChild(Module.ENTITIES, node);
  }

  public void insertEntities(Entity prev, Entity node) {
    this.insertChild(prev, Module.ENTITIES, node);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(Module.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, Module.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, Module.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(Module.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, Module.SMODEL_ATTRIBUTE, node);
  }

  public static Module newInstance(SModel sm, boolean init) {
    return (Module) SModelUtil_new.instantiateConceptDeclaration("entities.structure.Module", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static Module newInstance(SModel sm) {
    return Module.newInstance(sm, false);
  }
}
